[package]
name = "rdb"
version = "0.1.0"
authors = ["Luo Ji <weiqiyiji@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
crc = "1.8.1"
byteorder = "1.2.7"

[[bin]]
name = "main"
path = "src/bin/main.rs"